#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/users/token

gesdinet_jwt_refresh_token:
    path:     /api/users/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken::refresh }
